name: SirenUA
options:
  bundleIdPrefix: com.sirenua
targets:
  SirenUA:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources: 
      - path: Sources/SirenUA
    entitlements:
      path: Sources/SirenUA/SirenUA.entitlements
    dependencies:
      - package: Firebase
        product: FirebaseMessaging
    settings:
      base:
        INFOPLIST_FILE: Sources/SirenUA/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.sirenua.SirenUA
        SWIFT_VERSION: 5.0
        DEVELOPMENT_TEAM: "B7WVJ3B4B7"
        CODE_SIGNING_REQUIRED: "YES"
        CODE_SIGN_STYLE: Automatic
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
  SirenUATests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources: 
      - path: Tests/SirenUATests
    dependencies:
      - target: SirenUA
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES

packages:
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.0.0

schemes:
  SirenUA:
    build:
      targets:
        SirenUA: all
    run:
      config: Debug
      storeKitConfiguration: SirenUA.storekit
    test:
      targets:
        - SirenUATests
