name: SirenUA
options:
  bundleIdPrefix: com.sirenua
targets:
  SirenUA:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources: 
      - path: SirenUAApp.swift
      - path: AlertRegionDetailView.swift
      - path: NetworkManager.swift
      - path: AlertRegion.swift
      - path: ErrorView.swift
      - path: CriticalAlertManager.swift
      - path: SettingsView.swift
      - path: NotificationManager.swift
      - path: ContentView.swift
      - path: AlertViewModelV3.swift
      - path: GeoJSONManager.swift
      - path: ukraine_regions.geojson
      - path: LocationManager.swift
      - path: siren.wav
      - path: vidbiy.wav
    settings:
      base:
        INFOPLIST_FILE: Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.sirenua.SirenUA
        SWIFT_VERSION: 5.0
        DEVELOPMENT_TEAM: ""
  SirenUATests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources: 
      - path: Tests/SirenUATests
    dependencies:
      - target: SirenUA
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
