# Load the .env file
require 'dotenv'
Dotenv.load('.env', '../.env')

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    # Authenticate with App Store Connect API
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_PRIVATE_KEY_PATH"],
      in_house: false # Set to true if you are using an Enterprise account
    )

    # Automatically increment the build number (requires Generic Versioning to be enabled in Xcode)
    increment_build_number(
      build_number: latest_testflight_build_number(initial_build_number: 1) + 1
    )

    # Build the application
    build_app(
      scheme: "SirenUA",
      export_method: "app-store",
      xcargs: "-allowProvisioningUpdates",
      export_xcargs: "-allowProvisioningUpdates"
    )

    # Upload to TestFlight and distribute to specific groups
    upload_to_testflight(
      groups: ["Internal Testers Group", "External Testers"]
    )
  end

  desc "Upload metadata to App Store Connect"
  lane :upload_metadata do
    app_store_connect_api_key(
      key_id: ENV["ASC_KEY_ID"],
      issuer_id: ENV["ASC_ISSUER_ID"],
      key_filepath: ENV["ASC_PRIVATE_KEY_PATH"],
      in_house: false
    )

    upload_to_app_store(
      skip_binary_upload: true,
      skip_screenshots: true,
      force: true
    )
  end
end
